# Generated by Django 3.0.2 on 2020-01-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20200113_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usr',
            old_name='user',
            new_name='userr',
        ),
    ]
