# Generated by Django 3.0.2 on 2020-01-13 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0003_auto_20200113_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='usr',
            name='userr',
        ),
        migrations.AddField(
            model_name='usr',
            name='usr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
