# Generated by Django 3.0.2 on 2020-01-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20200113_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usr',
        ),
    ]
